In [1]:
import pandas as pd

In [29]:
na_vals = ["NA", "Missing"]

df = pd.read_csv("data.csv", low_memory=False, index_col="ResponseId", na_values=na_vals)

In [3]:
#Got a DtypeWarning because some columns have mixed data types. Fixed by passing low_memory=False to read_csv, which reads the entire file at once before inferring column types.

In [4]:
#you can specify how many
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [5]:
df.tail(10)

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
49182,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49183,I am a developer by profession,35-44 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49184,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,2.0,"Yes, I am new to coding or currently a student",Books / Physical media;Videos (not associated ...,"Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49185,"I am not primarily a developer, but I write co...",45-54 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,"Caring for dependents (children, elderly, etc....",30.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49186,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Number of rows and columns 
df.shape

(49191, 171)

In [7]:
#Number of rows and columns and all of the data type
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 1 to 49191
Columns: 171 entries, MainBranch to JobSat
dtypes: float64(52), str(119)
memory usage: 64.2 MB

In [8]:
df.dtypes

MainBranch                 str
Age                        str
EdLevel                    str
Employment                 str
EmploymentAddl             str
                        ...
AIAgentExtWrite            str
AIHuman                    str
AIOpen                     str
ConvertedCompYearly    float64
JobSat                 float64
Length: 171, dtype: object

In [9]:
pd.set_option('display.max_columns', 172)

In [10]:
schema_df= pd.read_csv('schema.csv', index_col="qname")

In [11]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [12]:
people = {
    "first": ["Corey", "Jane", "John", "Ada"],
    "last": ["Schafer", "Doe", "Doe", "Wong"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@email.com", "JohnDoe@email.com", "Ada@email.com"]
}

In [13]:
#Create a dataframe with the information above

In [14]:
df = pd.DataFrame(people)

In [15]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3    Ada     Wong            Ada@email.com

In [16]:
df["email"]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
3              Ada@email.com
Name: email, dtype: str

In [17]:
df.email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
3              Ada@email.com
Name: email, dtype: str

In [18]:
df[["last", "email"]]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com
3     Wong            Ada@email.com

In [19]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [20]:
#iloc = access rows and columns by integer location
df.iloc[[0,1], 2]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: str

In [21]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3    Ada     Wong            Ada@email.com

In [22]:
#loc = access rows and columns by label
df.loc[[0,1], ["first", "last"]]

   first     last
0  Corey  Schafer
1   Jane      Doe

In [23]:
df.shape

(4, 3)

In [24]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [25]:
list(df.columns)

['first', 'last', 'email']

In [26]:
#value_counts() returns the number of occurrences of each unique value in a column, sorted from most to least frequent.
df["Country"].value_counts()

KeyError: 'Country'

In [ ]:
#df.loc[row_label, column_label] - first argument is the row label, second is the column label.
df.loc[0:2, "Country":"LanguageChoice"]

In [ ]:
df["email"]

In [ ]:
df.set_index("email", inplace=True)

In [ ]:
df

In [ ]:
df.index

In [ ]:
df.loc["JohnDoe@email.com", "last"]

In [ ]:
df.iloc[0]

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

In [ ]:
list(df.columns)

In [ ]:
schema_df.loc["YearsCode", "question"]

In [ ]:
schema_df.sort_index()

In [ ]:
filt = (df["last"] == "Schafer") | (df["first"] == "John")

In [ ]:
df.loc[~filt, "email"]

In [ ]:
countries = ["United States", "Brazil", "Ukraine","Canada", "Russia"]
high_salary = (df["ConvertedCompYearly"] > 180000) & (df["Country"].isin(countries)) & (df["LanguageHaveWorkedWith"].str.contains("Python", na=False))

In [ ]:
df.loc[high_salary, ["Country", "LanguageHaveWorkedWith", "WorkExp", "ConvertedCompYearly"]]

In [ ]:
filt = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

In [ ]:
df.loc[filt, "LanguageHaveWorkedWith"]

In [ ]:
df

In [ ]:
df.columns

In [ ]:
#Rename all columns name

In [ ]:
df.columns = ["first_name", "last_name", "email"]

In [ ]:
df

In [ ]:
#Uppercase all

df.columns= [x.lower() for x in df.columns]
df

In [ ]:
df.columns = df.columns.str.replace(" ", "_")
df

In [ ]:
#Change Some Columns

df.rename(columns={"first_name": "first",
                   "last_name":  "last"}, inplace=True)

df

In [ ]:
df.loc[2, ["last", "email"]] = ["Smith", "JohnSmith@email.com"]

In [ ]:
 df

In [ ]:
df.loc[2, "last"] = "Doe"

In [ ]:
df

In [ ]:
df.at[2, "email"] = "JohnDoe@email.com"

In [ ]:
df

In [ ]:
filt = (df["email"] == "JohnDoe@email.com")
df.loc[filt, "last"] = "Smith"

In [ ]:
df

In [ ]:
df["email"] = df["email"].str.lower()

In [ ]:
df

In [ ]:
apply
map
applymap
replace

In [ ]:
df["email"].apply(len)

In [ ]:
def update_email(email):
    return email.upper()

In [ ]:
#apply() takes a function and applies it to every element in a column. Can be used with a named function or a lambda for concise one-liners.

df["email"].apply(update_email)

In [ ]:
df["email"].apply(lambda x: x.lower())

In [ ]:
df["email"].apply(len)

In [ ]:
df.apply(pd.Series.min)

In [ ]:
df.apply(lambda x: x.min())

In [ ]:
df.map(len)

In [ ]:
df.map(str.lower)

In [ ]:
df["first"].map({"Corey": "Caio"})

In [ ]:
df["first"] = df["first"].replace({"Corey": "Caio"})

In [ ]:
df

In [ ]:
df.rename(columns = {"ConvertedCompYearly": "SalaryUSDYearly"})

In [ ]:
df

In [ ]:
df["first"] + "  " + df["last"]

In [ ]:
df["full_name"] = df["first"] + "  " + df["last"]
df

In [ ]:
df.drop(columns=["first", "last"], inplace=True)

In [ ]:
df

In [ ]:
df["full_name"].str.split("  ", expand=True)

In [ ]:
df[["first", "last"]] = df["full_name"].str.split("  ", expand=True)

In [ ]:
df

In [ ]:
pd.concat([df, pd.DataFrame({"first": ["Tony"]})], ignore_index=True)

In [ ]:
people = {
    "first": ["Zé", "Balão"],
    "last": ["Hanna", "Marin"],
    "email": ["darksouls@gmail.com", "soulsdark@email.com"]
}

df2 = pd.DataFrame(people)

In [ ]:
df2

In [ ]:
df3 = pd.concat([df, df2], ignore_index=True)

In [ ]:
df3

In [ ]:
df3.drop(index=4)

In [ ]:
# 1. df["last"] == "Doe" - creates a boolean mask, True where last name is "Doe"
# 2. df[mask] - filters the DataFrame, returning only the rows where mask is True
# 3. .index - gets the index labels of those filtered rows
# 4. df.drop(index=...) - drops the rows with those index labels from the DataFrame
df.drop(index=df[df["last"] == "Doe"].index)

In [ ]:
df.sort_values(by="last", ascending=False)

In [ ]:
df.sort_values(by=["last", "first"], ascending=False)

In [ ]:
df.sort_values(by=["last", "first"], ascending=[False, True], inplace=True)

In [ ]:
df

In [ ]:
df.sort_index()

In [ ]:
df["last"].sort_values()

In [ ]:
df.sort_values(by=["Country", "ConvertedCompYearly"], ascending=[True, False], inplace=True)

In [ ]:
df[["Country", "ConvertedCompYearly"]].head(50)

In [ ]:
df["ConvertedCompYearly"].nlargest(10)

In [ ]:
df.nlargest(10, "ConvertedCompYearly")

In [ ]:
df.nsmallest(10, "ConvertedCompYearly")

In [ ]:
df["ConvertedCompYearly"].head(15)

In [ ]:
df["ConvertedCompYearly"].median()

In [ ]:
df.describe()

In [ ]:
df["ConvertedCompYearly"].count()

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.head()

In [ ]:
df["LanguageChoice"].value_counts()

In [ ]:
pd.set_option('display.max_rows', None)
schema_df

In [ ]:
schema_df.loc["LanguageChoice", "question"]

In [ ]:
df["AIAgentKnowWrite"].value_counts()

In [ ]:
df["Country"].value_counts()

In [ ]:
country_grp = df.groupby("Country")
country_grp.get_group("South Korea")

In [ ]:
filt =df["Country"] == "South Korea"

In [ ]:
df.loc[filt]

In [ ]:
country_grp["ConvertedCompYearly"].value_counts().head(50)

In [ ]:
country_grp["ConvertedCompYearly"].median().loc["Ukraine"]

In [ ]:
country_grp["ConvertedCompYearly"].agg(["median", "mean"])

In [ ]:
filt =df["Country"] == "South Korea"
df.loc[filt]["LanguageHaveWorkedWith"].str.contains("Python").sum()

In [ ]:
country_grp["LanguageHaveWorkedWith"].apply(lambda x: x.str.contains("Python").sum() / x.count() * 100)

In [30]:
df["YearsCode"].head(10)

ResponseId
1     14.0
2     10.0
3     12.0
4      5.0
5     22.0
6     20.0
7     13.0
8     30.0
9     15.0
10    10.0
Name: YearsCode, dtype: float64

In [33]:
df.dtypes["YearsCode"]

dtype('float64')

In [34]:
df["YearsCode"].mean()

np.float64(16.570861019469355)

In [35]:
df["YearsCode"].isna().sum()
df["YearsCode"].count()

np.int64(43042)

In [37]:
df["YearsCode"].describe()

count    43042.000000
mean        16.570861
std         11.787610
min          1.000000
25%          8.000000
50%         14.000000
75%         24.000000
max        100.000000
Name: YearsCode, dtype: float64

In [40]:
df["YearsCode"].unique()

array([ 14.,  10.,  12.,   5.,  22.,  20.,  13.,  30.,  15.,   9.,   6.,
        nan,   3.,  40.,   8.,  45.,  35.,  11.,   7.,  47.,  41.,  36.,
        23.,  29.,  26.,  25.,  38.,  21.,  19.,  18.,  16.,   4.,  17.,
        42.,  27.,  24.,   2.,  28.,  37.,  32.,   1.,  39.,  53.,  33.,
        50.,  48.,  44.,  31.,  46.,  43.,  49.,  52.,  34.,  51.,  58.,
        57.,  54.,  63.,  60.,  55.,  65., 100.,  99.,  56.,  69.,  90.,
        61.,  67.,  75.,  64.,  98.,  68.,  89.,  62.,  78.,  70.,  76.,
        82.,  59.])

In [41]:
df["YearsCode"].dropna()

ResponseId
1        14.0
2        10.0
3        12.0
4         5.0
5        22.0
         ...
49180    12.0
49181     7.0
49184     2.0
49189    31.0
49191     6.0
Name: YearsCode, Length: 43042, dtype: float64