In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv", low_memory=False, index_col="ResponseId")

In [3]:
#Got a DtypeWarning because some columns have mixed data types. Fixed by passing low_memory=False to read_csv, which reads the entire file at once before inferring column types.

In [21]:
#you can specify how many
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [5]:
df.tail(10)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
49181,49182,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49182,49183,I am a developer by profession,35-44 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49183,49184,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,2.0,"Yes, I am new to coding or currently a student",Books / Physical media;Videos (not associated ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49184,49185,"I am not primarily a developer, but I write co...",45-54 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,"Caring for dependents (children, elderly, etc....",30.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49185,49186,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Number of rows and columns 
df.shape

(49191, 172)

In [7]:
#Number of rows and columns and all of the data type
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [8]:
df.dtypes

ResponseId               int64
MainBranch                 str
Age                        str
EdLevel                    str
Employment                 str
                        ...
AIAgentExtWrite            str
AIHuman                    str
AIOpen                     str
ConvertedCompYearly    float64
JobSat                 float64
Length: 172, dtype: object

In [9]:
pd.set_option('display.max_columns', 172)

In [14]:
schema_df= pd.read_csv('schema.csv', index_col="qname")

In [11]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [7]:
people = {
    "first": ["Corey", "Jane", "John", "Ada"],
    "last": ["Schafer", "Doe", "Doe", "Wong"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@email.com", "JohnDoe@email.com", "Ada@email.com"]
}

In [8]:
#Create a dataframe with the information above

In [9]:
df = pd.DataFrame(people)

In [10]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [16]:
df["email"]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [17]:
df.email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [18]:
df[["last", "email"]]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [19]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [20]:
#iloc = access rows and columns by integer location
df.iloc[[0,1], 2]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: str

In [21]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [22]:
#loc = access rows and columns by label
df.loc[[0,1], ["first", "last"]]

   first     last
0  Corey  Schafer
1   Jane      Doe

In [23]:
df.shape

(3, 3)

In [25]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [26]:
list(df.columns)

['first', 'last', 'email']

In [33]:
#value_counts() returns the number of occurrences of each unique value in a column, sorted from most to least frequent.
df["Country"].value_counts()

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
                                                        ...
San Marino                                                 1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, Length: 177, dtype: int64

In [34]:
#df.loc[row_label, column_label] - first argument is the row label, second is the column label.
df.loc[0:2, "Country":"LanguageChoice"]

       Country               Currency  CompTotal LanguageChoice
0      Ukraine      EUR European Euro    52800.0            Yes
1  Netherlands      EUR European Euro    90000.0            Yes
2      Ukraine  UAH Ukrainian hryvnia  2214000.0            Yes

In [38]:
df["email"]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [42]:
df.set_index("email", inplace=True)

In [43]:
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [44]:
df.index

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='str', name='email')

In [47]:
df.loc["JohnDoe@email.com", "last"]

'Doe'

In [49]:
df.iloc[0]

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: str

In [50]:
df.reset_index(inplace=True)

In [51]:
df

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe

In [68]:
list(df.columns)

['MainBranch',
 'Age',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'WorkExp',
 'LearnCodeChoose',
 'LearnCode',
 'LearnCodeAI',
 'AILearnHow',
 'YearsCode',
 'DevType',
 'OrgSize',
 'ICorPM',
 'RemoteWork',
 'PurchaseInfluence',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechOppose_1',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_16',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_16',
 'JobSatPoints_15_TEXT',
 'AIThreat',
 'NewRole',
 'ToolCountWork',
 'ToolCountPersonal',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseChoice',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'PlatformChoice',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeChoice',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvsChoice',
 'DevEnvsHaveWorkedWith',
 'DevEnvsWantToWorkWith',
 'DevEnvsAdmired',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveWorkedWith',
 'SOTagsWantToWorkWith',
 'SOTagsAdmired',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveWorkedWith',
 'CommPlatformWantToWorkWith',
 'CommPlatformAdmired',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIModelsChoice',
 'AIModelsHaveWorkedWith',
 'AIModelsWantToWorkWith',
 'AIModelsAdmired',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'SOAccount',
 'SOVisitFreq',
 'SODuration',
 'SOPartFreq',
 'SO_Dev_Content',
 'SO_Actions_1',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_9',
 'SO_Actions_7',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SOComm',
 'SOFriction',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently partially AI',
 "AIToolDon't plan to use AI for this task",
 'AIToolPlan to partially use AI',
 'AIToolPlan to mostly use AI',
 'AIToolCurrently mostly AI',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AgentUsesGeneral',
 'AIAgentImpactSomewhat agree',
 'AIAgentImpactNeutral',
 'AIAgentImpactSomewhat disagree',
 'AIAgentImpactStrongly agree',
 'AIAgentImpactStrongly disagree',
 'AIAgentChallengesNeutral',
 'AIAgentChallengesSomewhat disagree',
 'AIAgentChallengesStrongly agree',
 'AIAgentChallengesSomewhat agree',
 'AIAgentChallengesStrongly disagree',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen',
 'ConvertedCompYearly',
 'JobSat']

In [72]:
schema_df.loc["YearsCode", "question"]

'Including any education, how many years have you been coding in total?  Please round to the nearest whole number, excluding any decimal points.'

In [71]:
schema_df.sort_index()

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
...,...,...,...,...,...
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [15]:
filt = (df["last"] == "Schafer") | (df["first"] == "John")

In [18]:
df.loc[~filt, "email"]

1    JaneDoe@email.com
Name: email, dtype: str

In [43]:
countries = ["United States", "Brazil", "Ukraine","Canada", "Russia"]
high_salary = (df["ConvertedCompYearly"] > 180000) & (df["Country"].isin(countries)) & (df["LanguageHaveWorkedWith"].str.contains("Python", na=False))

In [44]:
df.loc[high_salary, ["Country", "LanguageHaveWorkedWith", "WorkExp", "ConvertedCompYearly"]]

,Country,LanguageHaveWorkedWith,WorkExp,ConvertedCompYearly
ResponseId,,,,
544,Canada,C;C++;Kotlin;Python,30.0,218875.0
957,Canada,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,25.0,221064.0
1046,Canada,HTML/CSS;JavaScript;Python;Ruby;SQL;TypeScript,16.0,248058.0
1281,Canada,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...,19.0,218875.0
2096,Canada,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,21.0,200635.0
2145,Canada,Bash/Shell (all shells);Java;Python,19.0,364792.0
2310,Canada,HTML/CSS;Java;JavaScript;Python;Ruby;SQL,16.0,198447.0
2536,Canada,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,10.0,196988.0
2962,Canada,Bash/Shell (all shells);Dart;HTML/CSS;JavaScri...,4.0,210000.0
3082,Canada,Delphi;Python;SQL,35.0,182396.0
3415,Canada,Bash/Shell (all shells);C#;C++;Groovy;Lua;Powe...,23.0,350200.0
4871,Canada,Bash/Shell (all shells);Python;Swift,8.0,218875.0
4906,Canada,C;C++;Go;Groovy;HTML/CSS;Java;Python;Rust;SQL,30.0,284538.0
5415,Canada,Bash/Shell (all shells);PHP;Python;Ruby;Rust,10.0,204283.0
5770,Canada,Bash/Shell (all shells);C++;Python;Rust,45.0,185000.0
5846,Canada,Assembly;C;C#;GDScript;Go;HTML/CSS;JavaScript;...,20.0,182396.0
5953,Canada,HTML/CSS;JavaScript;Python;SQL,4.0,729584.0
8604,Canada,Python;SQL,10.0,200635.0
8632,Canada,Java;JavaScript;Python;Scala;SQL,10.0,277242.0
11118,Canada,Bash/Shell (all shells);HTML/CSS;Python;Scala;...,20.0,218875.0
11275,Brazil,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,20.0,210252.0
11407,Canada,Bash/Shell (all shells);C;Java;JavaScript;Pyth...,23.0,182396.0
11825,Canada,C++;Python;Rust;TypeScript,10.0,510708.0
12078,Canada,Bash/Shell (all shells);C#;Java;JavaScript;Pyt...,18.0,183456.0
14243,Canada,Bash/Shell (all shells);Go;JavaScript;Python;T...,25.0,189692.0
16954,Canada,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...,12.0,182396.0
18194,Canada,HTML/CSS;JavaScript;Kotlin;Python;SQL;TypeScript,17.0,182396.0
18825,Canada,Bash/Shell (all shells);C;C++;Go;Java;JavaScri...,7.0,218875.0
19019,Canada,Bash/Shell (all shells);C;C++;HTML/CSS;MATLAB;...,13.0,200635.0
20866,Canada,Assembly;Bash/Shell (all shells);C++;Python;Rust,10.0,364792.0
21017,Canada,Assembly;C#;C++;HTML/CSS;JavaScript;Perl;PHP;P...,30.0,196988.0
23399,Canada,Java;JavaScript;Lua;Perl;Python;TypeScript,18.0,240763.0
24044,Canada,Assembly;Bash/Shell (all shells);C;C#;C++;Go;H...,30.0,452342.0
26501,Canada,Elixir;Go;HTML/CSS;JavaScript;Python;Ruby;Rust...,15.0,199176.0
26599,Canada,Bash/Shell (all shells);Erlang;Go;HTML/CSS;Jav...,30.0,182396.0
27272,Canada,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,20.0,189692.0
27345,Canada,Bash/Shell (all shells);C;C++;HTML/CSS;JavaScr...,16.0,182396.0
27378,Canada,Go;Python,13.0,237115.0
28225,Canada,Bash/Shell (all shells);GDScript;Go;HTML/CSS;J...,20.0,229819.0
30182,Canada,Bash/Shell (all shells);JavaScript;Lua;PowerSh...,10.0,218875.0
30616,Canada,Assembly;Bash/Shell (all shells);C;HTML/CSS;Ja...,17.0,182396.0
30729,Brazil,Bash/Shell (all shells);Elixir;Go;Kotlin;Python,17.0,6371285.0
31599,Canada,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,2.0,218875.0
31956,Canada,Bash/Shell (all shells);C;C++;Java;JavaScript;...,48.0,542810.0
35675,Brazil,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,1.0,182037.0
35687,Canada,C;C++;HTML/CSS;JavaScript;Python;Ruby;Rust;Swift,8.0,242951.0
37367,Canada,Java;Kotlin;Python;SQL,5.0,583667.0
38571,Canada,Bash/Shell (all shells);Go;Python,16.0,215227.0
40342,Canada,Bash/Shell (all shells);C;C++;Java;JavaScript;...,15.0,182396.0
40576,Canada,Assembly;Bash/Shell (all shells);C;C++;Go;Lua;...,21.0,218875.0
40783,Canada,C;Go;Python,9.0,182396.0
44880,Canada,Go;Python,15.0,200635.0
44958,Canada,Bash/Shell (all shells);C#;GDScript;Go;JavaScr...,15.0,218875.0
45580,Canada,HTML/CSS;JavaScript;Python;SQL;TypeScript,15.0,189692.0
45837,Canada,Bash/Shell (all shells);JavaScript;Perl;Python...,30.0,182396.0
48429,Ukraine,Assembly;C#;GDScript;HTML/CSS;JavaScript;Micro...,NaN,10000000.0

In [39]:
filt = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

In [41]:
df.loc[filt, "LanguageHaveWorkedWith"]

ResponseId
5        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
8        Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
9                                        Java;Python;Scala
16       Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...
18                          HTML/CSS;JavaScript;Python;SQL
                               ...
49144            HTML/CSS;JavaScript;Python;SQL;TypeScript
49146    Assembly;Bash/Shell (all shells);C;C++;Python;...
49176    Bash/Shell (all shells);C#;C++;GDScript;HTML/C...
49177    Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
49178    Bash/Shell (all shells);HTML/CSS;Lisp;PowerShe...
Name: LanguageHaveWorkedWith, Length: 18466, dtype: str

In [10]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [11]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [ ]:
#Rename all columns name

In [12]:
df.columns = ["first_name", "last_name", "email"]

In [13]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [24]:
#Uppercase all

df.columns= [x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [25]:
df.columns = df.columns.str.replace(" ", "_")
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [29]:
#Change Some Columns

df.rename(columns={"first_name": "first",
                   "last_name":  "last"}, inplace=True)

df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [36]:
df.loc[2, ["last", "email"]] = ["Smith", "JohnSmith@email.com"]

In [37]:
 df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JohnSmith@email.com

In [40]:
df.loc[2, "last"] = "Doe"

In [41]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe      JohnSmith@email.com

In [42]:
df.at[2, "email"] = "JohnDoe@email.com"

In [43]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [54]:
filt = (df["email"] == "JohnDoe@email.com")
df.loc[filt, "last"] = "Smith"

In [55]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith        JohnDoe@email.com

In [59]:
df["email"] = df["email"].str.lower()

In [61]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John    Smith        johndoe@email.com

In [ ]:
apply
map
applymap
replace

In [62]:
df["email"].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [66]:
def update_email(email):
    return email.upper()

In [67]:
#apply() takes a function and applies it to every element in a column. Can be used with a named function or a lambda for concise one-liners.

df["email"].apply(update_email)

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2          JOHNDOE@EMAIL.COM
Name: email, dtype: str

In [7]:
df["email"].apply(lambda x: x.lower())

0    coreymschafer@gmail.com
1          janedoe@email.com
2          johndoe@email.com
Name: email, dtype: str

In [8]:
df["email"].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [9]:
df.apply(pd.Series.min)

first                      Corey
last                         Doe
email    CoreyMSchafer@gmail.com
dtype: str

In [12]:
df.apply(lambda x: x.min())

first                      Corey
last                         Doe
email    CoreyMSchafer@gmail.com
dtype: str

In [14]:
df.map(len)

   first  last  email
0      5     7     23
1      4     3     17
2      4     3     17

In [16]:
df.map(str.lower)

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@email.com
2   john      doe        johndoe@email.com

In [26]:
df["first"].map({"Corey": "Caio"})

0    Caio
1     NaN
2     NaN
Name: first, dtype: str

In [28]:
df["first"] = df["first"].replace({"Corey": "Caio"})

In [31]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.rename(columns = {"ConvertedCompYearly": "SalaryUSDYearly"})

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSDYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df["first"] + "  " + df["last"]

0    Corey  Schafer
1         Jane  Doe
2         John  Doe
dtype: str

In [13]:
df["full_name"] = df["first"] + "  " + df["last"]
df

   first     last                    email       full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey  Schafer
1   Jane      Doe        JaneDoe@email.com       Jane  Doe
2   John      Doe        JohnDoe@email.com       John  Doe

In [15]:
df.drop(columns=["first", "last"], inplace=True)

In [16]:
df

                     email       full_name
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe
2        JohnDoe@email.com       John  Doe

In [18]:
df["full_name"].str.split("  ", expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [21]:
df[["first", "last"]] = df["full_name"].str.split("  ", expand=True)

In [22]:
df

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe   Jane      Doe
2        JohnDoe@email.com       John  Doe   John      Doe

In [27]:
pd.concat([df, pd.DataFrame({"first": ["Tony"]})], ignore_index=True)

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe   Jane      Doe
2        JohnDoe@email.com       John  Doe   John      Doe
3                      NaN             NaN   Tony      NaN

In [28]:
people = {
    "first": ["Zé", "Balão"],
    "last": ["Hanna", "Marin"],
    "email": ["darksouls@gmail.com", "soulsdark@email.com"]
}

df2 = pd.DataFrame(people)

In [29]:
df2

   first   last                email
0     Zé  Hanna  darksouls@gmail.com
1  Balão  Marin  soulsdark@email.com

In [34]:
df3 = pd.concat([df, df2], ignore_index=True)

In [35]:
df3

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe   Jane      Doe
2        JohnDoe@email.com       John  Doe   John      Doe
3      darksouls@gmail.com             NaN     Zé    Hanna
4      soulsdark@email.com             NaN  Balão    Marin

In [37]:
df3.drop(index=4)

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe   Jane      Doe
2        JohnDoe@email.com       John  Doe   John      Doe
3      darksouls@gmail.com             NaN     Zé    Hanna

In [40]:
# 1. df["last"] == "Doe" - creates a boolean mask, True where last name is "Doe"
# 2. df[mask] - filters the DataFrame, returning only the rows where mask is True
# 3. .index - gets the index labels of those filtered rows
# 4. df.drop(index=...) - drops the rows with those index labels from the DataFrame
df.drop(index=df[df["last"] == "Doe"].index)

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer

In [10]:
df.sort_values(by="last", ascending=False)

   first     last                    email
3    Ada     Wong            Ada@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [12]:
df.sort_values(by=["last", "first"], ascending=False)

   first     last                    email
3    Ada     Wong            Ada@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@email.com
1   Jane      Doe        JaneDoe@email.com

In [14]:
df.sort_values(by=["last", "first"], ascending=[False, True], inplace=True)

In [15]:
df

   first     last                    email
3    Ada     Wong            Ada@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [18]:
df.sort_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3    Ada     Wong            Ada@email.com

In [19]:
df["last"].sort_values()

1        Doe
2        Doe
0    Schafer
3       Wong
Name: last, dtype: str

In [30]:
df.sort_values(by=["Country", "ConvertedCompYearly"], ascending=[True, False], inplace=True)

In [31]:
df[["Country", "ConvertedCompYearly"]].head(50)

                Country  ConvertedCompYearly
ResponseId
40967       Afghanistan              65000.0
40307       Afghanistan               9858.0
7077        Afghanistan               8450.0
45925       Afghanistan               7042.0
7167        Afghanistan               5200.0
38609       Afghanistan               1000.0
6010        Afghanistan                986.0
7925        Afghanistan                282.0
6836        Afghanistan                  NaN
15708       Afghanistan                  NaN
19816       Afghanistan                  NaN
44797       Afghanistan                  NaN
27099       Afghanistan                  NaN
2023            Albania             139218.0
28588           Albania             118286.0
3185            Albania             116014.0
37731           Albania              67779.0
35934           Albania              50000.0
14758           Albania              34804.0
33940           Albania              17734.0
48950           Albania              17402.0
3888            Albania              14187.0
16850           Albania                236.0
22400           Albania                 15.0
27802           Albania                  8.0
36997           Albania                  NaN
35184           Albania                  NaN
16239           Albania                  NaN
45421           Albania                  NaN
44879           Albania                  NaN
44946           Albania                  NaN
8776            Albania                  NaN
11874           Albania                  NaN
41907           Albania                  NaN
25304           Albania                  NaN
41296           Algeria              98612.0
37619           Algeria              50000.0
26446           Algeria              23114.0
1541            Algeria              20883.0
23091           Algeria              12000.0
29465           Algeria               7705.0
16686           Algeria               7088.0
30107           Algeria               6472.0
1841            Algeria               4438.0
31352           Algeria               3852.0
46636           Algeria               2400.0
14548           Algeria               1156.0
34029           Algeria               1109.0
25845           Algeria                185.0
11322           Algeria                 17.0

In [34]:
df["ConvertedCompYearly"].nlargest(10)

ResponseId
34268    50000000.0
28701    33552715.0
43144    18387548.0
35354    15430267.0
45972    13921760.0
48429    10000000.0
24901     9531653.0
10026     9000000.0
37353     6890299.0
30729     6371285.0
Name: ConvertedCompYearly, dtype: float64

In [38]:
df.nlargest(10, "ConvertedCompYearly")

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
34268,I code primarily as a hobby,55-64 years old,"Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000000.0,NaN
28701,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I have et...,NaN,33552715.0,7.0
43144,I code primarily as a hobby,18-24 years old,"Associate degree (A.A., A.S., etc.)",Employed,Engaged in paid work (20-29 hours per week);En...,10.0,"Yes, I am not new to coding but am learning ne...",Other (please specify):,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,being laid off,18387548.0,NaN
35354,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,ChatGPT;Google Gemini,NaN,When I’m stuck and can’t explain the problem,NaN,15430267.0,8.0
45972,I work with developers or my work supports dev...,55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),30.0,"Yes, I am not new to coding but am learning ne...",Colleague or on-the-job training,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13921760.0,NaN
48429,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (10-19 hours per week);En...,NaN,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000000.0,NaN
24901,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,9531653.0,4.0
10026,I am a developer by profession,25-34 years old,Primary/elementary school,Employed,Attending school (full-time),2.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Everything,9000000.0,9.0
37353,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Volunteering (regularly),15.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,"All the same: right tools for proper tasks, co...",6890299.0,7.0
30729,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Attending school (part-time);Engaged in paid w...,17.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"problem synthesis, communication, panoramic vi...",6371285.0,8.0

In [39]:
df.nsmallest(10, "ConvertedCompYearly")

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
34866,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (less than 10 hours per w...,16.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,Ollama,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemi...,NaN,When I don’t trust AI’s answers;When I want to...,all of them,1.0,8.0
41683,"I am not primarily a developer, but I write co...",45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",None of the above,13.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something,AI provides the code but if it is not somethin...,1.0,NaN
34568,I am a developer by profession,25-34 years old,Primary/elementary school,Employed,Volunteering (regularly),8.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0
27893,I am learning to code,35-44 years old,Some college/university study without earning ...,Not employed,None of the above,12.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
28178,I am a developer by profession,18-24 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",Volunteering (regularly);Engaged in paid work ...,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Solve any problem with logic,1.0,8.0
42079,I work with developers or my work supports dev...,25-34 years old,Some college/university study without earning ...,Student,Attending school (full-time),12.0,"Yes, I am new to coding or currently a student","School (i.e., University, College, etc)","Yes, I learned how to use AI-enabled tools req...","Other online resources (e.g. standard search, ...",...,Amazon Bedrock Agents,NaN,Adversarial Robustness Toolbox (ART),NaN,OpenHands (formerly OpenDevin),NaN,When I want to fully understand something,Mentioned,1.0,NaN
16490,I am learning to code,18-24 years old,Primary/elementary school,"Independent contractor, freelancer, or self-em...",Volunteering (regularly),1.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4581,I am a developer by profession,18-24 years old,"Associate degree (A.A., A.S., etc.)",Student,Attending school (full-time);Engaged in paid w...,6.0,"Yes, I am new to coding or currently a student","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,NaN,1.0,8.0
21035,I am a developer by profession,18-24 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Not employed,"Caring for dependents (children, elderly, etc.)",1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,...,Zapier,NaN,Langfuse,NaN,ChatGPT;Bolt.new,NaN,When I need quick help troubleshooting,Well it will gradually take to a killing path,1.0,6.0
26962,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),11.0,"Yes, I am not new to coding but am learning ne...",AI CodeGen tools or AI-enabled apps,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,CrewAI;LangChain;LangGraph,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0

In [3]:
df["ConvertedCompYearly"].head(15)

ResponseId
1      61256.0
2     104413.0
3      53061.0
4      36197.0
5      60000.0
6     120000.0
7       6240.0
8      72000.0
9      70000.0
10      5400.0
11     65691.0
12     14400.0
13      1099.0
14         NaN
15         NaN
Name: ConvertedCompYearly, dtype: float64

In [4]:
df["ConvertedCompYearly"].median()

np.float64(75320.0)

In [7]:
df.describe()

,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,...,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,...,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,4.370841,...,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,2.357058,...,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,2.000000,...,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,4.000000,...,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,6.000000,...,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,...,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [8]:
df["ConvertedCompYearly"].count()

np.int64(23947)

In [10]:
pd.set_option('display.max_columns', None)

In [11]:
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [12]:
df["LanguageChoice"].value_counts()

LanguageChoice
Yes    31553
No       661
Name: count, dtype: int64

In [15]:
pd.set_option('display.max_rows', None)
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [19]:
schema_df.loc["LanguageChoice", "question"]

'Did you work with programming, scripting and markup languages in the last year or do you plan to in the year to come?  Here, we are referring to anything you use that is conventionally referred to as code.'

In [20]:
df["AIAgentKnowWrite"].value_counts()

AIAgentKnowWrite
Copilot                                                                                                                                                                                                                                                                                                                           15
n8n                                                                                                                                                                                                                                                                                                                               15
Cursor                                                                                                                                                                                                                                                                                                                            13
ChatGPT                                                                                                                                                                                                                                                                                                                           13
Junie                                                                                                                                                                                                                                                                                                                             12
no                                                                                                                                                                                                                                                                                                                                 9
Claude Code                                                                                                                                                                                                                                                                                                                        8
copilot                                                                                                                                                                                                                                                                                                                            7
LangChain                                                                                                                                                                                                                                                                                                                          7
Langchain                                                                                                                                                                                                                                                                                                                          7
No                                                                                                                                                                                                                                                                                                                                 7
cursor                                                                                                                                                                                                                                                                                                                             7
Github Copilot                                                                                                                                                                                                                                                                                                                     7
custom                                                                                                                                                                                                                                                                                                                             6
GitHub Copilot                                                                                                                                                                                                                                                                                                                     6
chatgpt                                                                                                                                                                                                                                                                                                                            5
1                                                                                                                                                                                                                                                                                                                                  5
Azure AI Search                                                                                                                                                                                                                                                                                                                    4
Tidewave                                                                                                                                                                                                                                                                                                                           4
Cline                                                                                                                                                                                                                                                                                                                              4
yes                                                                                                                                                                                                                                                                                                                                4
Claude                                                                                                                                                                                                                                                                                                                             4
MongoDB                                                                                                                                                                                                                                                                                                                            3
LangGraph                                                                                                                                                                                                                                                                                                                          3
Gemini                                                                                                                                                                                                                                                                                                                             3
langgraph                                                                                                                                                                                                                                                                                                                          3
CoPilot                                                                                                                                                                                                                                                                                                                            3
LangChain, LangGraph                                                                                                                                                                                                                                                                                                               3
Custom                                                                                                                                                                                                                                                                                                                             3
Augment                                                                                                                                                                                                                                                                                                                            3
langchain                                                                                                                                                                                                                                                                                                                          3
Amazon Q                                                                                                                                                                                                                                                                                                                           3
Zed                                                                                                                                                                                                                                                                                                                                3
ollama                                                                                                                                                                                                                                                                                                                             2
opensearch                                                                                                                                                                                                                                                                                                                         2
SurrealDB                                                                                                                                                                                                                                                                                                                          2
ChatGPT, Gemini                                                                                                                                                                                                                                                                                                                    2
JetBrains AI                                                                                                                                                                                                                                                                                                                       2
Cursor AI                                                                                                                                                                                                                                                                                                                          2
zed                                                                                                                                                                                                                                                                                                                                2
Roo Code                                                                                                                                                                                                                                                                                                                           2
aider                                                                                                                                                                                                                                                                                                                              2
Codex                                                                                                                                                                                                                                                                                                                              2
Claude code                                                                                                                                                                                                                                                                                                                        2
Mastra                                                                                                                                                                                                                                                                                                                             2
Dify                                                                                                                                                                                                                                                                                                                               2
Agno                                                                                                                                                                                                                                                                                                                               2
Warp                                                                                                                                                                                                                                                                                                                               2
github copilot                                                                                                                                                                                                                                                                                                                     2
pydantic-ai                                                                                                                                                                                                                                                                                                                        2
Context7                                                                                                                                                                                                                                                                                                                           2
Co-pilot                                                                                                                                                                                                                                                                                                                           2
Microsoft Semantic Kernel                                                                                                                                                                                                                                                                                                          2
Semantic Kernel                                                                                                                                                                                                                                                                                                                    2
LlamaIndex                                                                                                                                                                                                                                                                                                                         2
3                                                                                                                                                                                                                                                                                                                                  2
Chatgpt                                                                                                                                                                                                                                                                                                                            2
Github copilot                                                                                                                                                                                                                                                                                                                     2
na                                                                                                                                                                                                                                                                                                                                 2
OpenSearch                                                                                                                                                                                                                                                                                                                         2
Spring AI                                                                                                                                                                                                                                                                                                                          2

In [37]:
df["Country"].value_counts()

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
Canada                                                  1305
Ukraine                                                  964
Poland                                                   888
Netherlands                                              867
Italy                                                    835
Brazil                                                   825
Australia                                                804
Spain                                                    717
Sweden                                                   616
Switzerland                                              546
Czech Republic                                           520
Austria                                                  410
Romania                                                  323
Belgium                                                  321
Denmark                                                  316
Israel                                                   297
Turkey                                                   295
Mexico                                                   286
Portugal                                                 280
China                                                    255
New Zealand                                              255
Finland                                                  254
South Africa                                             253
Greece                                                   252
Bulgaria                                                 244
Pakistan                                                 239
Norway                                                   237
Hungary                                                  236
Argentina                                                222
Bangladesh                                               220
Ireland                                                  209
Colombia                                                 202
Russian Federation                                       200
Nigeria                                                  199
Japan                                                    188
Indonesia                                                181
Serbia                                                   158
Iran, Islamic Republic of...                             149
Kenya                                                    148
Slovakia                                                 147
Viet Nam                                                 145
Philippines                                              142
Egypt                                                    140
Chile                                                    131
Thailand                                                 119
Taiwan                                                   118
Croatia                                                  113
Lithuania                                                101
Sri Lanka                                                 95
United Arab Emirates                                      89
Singapore                                                 89
Nepal                                                     83
Malaysia                                                  82
Slovenia                                                  78
Hong Kong (S.A.R.)                                        72
Estonia                                                   70
Peru                                                      64
Latvia                                                    62
Morocco                                                   55
Uruguay                                                   52
Algeria                                                   49
Georgia                                                   48
South Korea                                               48
Venezuela, Bolivarian Republic of...                      47
Tunisia                                                   46
Ghana                                                     46
Cyprus                                                    39
Ethiopia                                                  38
Republic of Korea                                         38
Saudi Arabia                                              37
Guatemala                                                 33
Jordan                                                    32
Bosnia and Herzegovina                                    30
Kazakhstan                                                29
Nomadic                                                   29
Uganda                                                    28
Ecuador                                                   28
Costa Rica                                                27
Dominican Republic                                        26
Belarus                                                   26
Armenia                                                   25
Luxembourg                                                23
Albania                                                   22
Paraguay                                                  21
Republic of North Macedonia                               20
Lebanon                                                   20
Malta                                                     19
Bolivia                                                   18
Yemen                                                     18
Azerbaijan                                                18
Myanmar                                                   17
Uzbekistan                                                16
Montenegro                                                15
Rwanda                                                    15
Zimbabwe                                                  13
Iraq                                                      13
Zambia                                                    13
Cameroon                                                  13
Afghanistan                                               13
Iceland                                                   13
El Salvador                                               12
Madagascar                                                11
Honduras                                                  11
Cambodia                                                  11
Mauritius                                                 11
Syrian Arab Republic                                      11
Kyrgyzstan                                                10
Panama                                                    10
Isle of Man                                               10
Togo                                                       9
Maldives                                                   9
Moldova                                                    9
Republic of Moldova                                        8
Côte d'Ivoire                                              8
Cuba                                                       8
Trinidad and Tobago                                        7
Bahrain                                                    7
Angola                                                     7
Palestine                                                  7
Namibia                                                    7
Democratic Republic of the Congo                           7
United Republic of Tanzania                                7
Kuwait                                                     7
Nicaragua                                                  6
Kosovo                                                     6
Oman                                                       6
North Korea                                                6
Andorra                                                    6
Qatar                                                      5
Mozambique                                                 5
Fiji                                                       5
Swaziland                                                  5
Benin                                                      5
Senegal                                                    5
Congo, Republic of the...                                  5
Democratic People's Republic of Korea                      4
Guyana                                                     4
Jamaica                                                    4
Somalia                                                    4
Barbados                                                   4
Malawi                                                     4
Sudan                                                      3
Belize                                                     3
Bhutan                                                     3
Brunei Darussalam                                          3
Mongolia                                                   3
Papua New Guinea                                           3
Saint Lucia                                                2
Haiti                                                      2
Tajikistan                                                 2
Suriname                                                   2
Botswana                                                   2
Micronesia, Federated States of...                         2
Mali                                                       2
Lao People's Democratic Republic                           2
Turkmenistan                                               2
Libyan Arab Jamahiriya                                     2
Antigua and Barbuda                                        2
Sierra Leone                                               2
Burundi                                                    2
Mauritania                                                 1
Timor-Leste                                                1
Gabon                                                      1
Guinea-Bissau                                              1
Gambia                                                     1
Niger                                                      1
Lesotho                                                    1
San Marino                                                 1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, dtype: int64

In [41]:
country_grp = df.groupby("Country")
country_grp.get_group("South Korea")

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
47927,"I used to be a developer by profession, but no...",25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not employed,Engaged in paid work (less than 10 hours per w...,5.0,"Yes, I am not new to coding but am learning ne...","Blogs or podcasts;School (i.e., University, Co...","No, I learned something that was not related t...",NaN,1.0,Student,"Just me - I am a freelancer, sole proprietor, ...",Individual contributor,Remote,"Yes, I endorsed a tool that was ultimately not...",School,1.0,7.0,6.0,4.0,9.0,2.0,3.0,5.0,8.0,10.0,NaN,9.0,6.0,7.0,5.0,2.0,1.0,3.0,8.0,4.0,10.0,NaN,Higher Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,55.0,66.0,Palau,USD United States dollar,NaN,NaN,Bash/Shell (all shells);COBOL;Dart;Delphi;Elix...,Ada;C;C#;C++;Erlang,NaN,NaN,NaN,NaN,Cloud Firestore;Databricks SQL;Datomic;DuckDB;...,BigQuery;Cassandra;Cosmos DB;Elasticsearch;H2;...,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not sure/can't remember,A few times per week,Between 1 and 3 years,Daily or almost daily,Job board,2.0,9.0,8.0,6.0,4.0,5.0,7.0,3.0,1.0,10.0,NaN,"Yes, definitely",I don't use AI or AI-enabled tools,"No, but I plan to soon",Unsure,Neither trust nor distrust,"Good, but not great at handling complex tasks",Other (write in):,Committing and reviewing code;Creating or main...,Learning about a codebase;Writing code;Testing...,Project planning;Predictive analytics;Generati...,Documenting code;Deployment and monitoring;Sea...,I’ve become less confident in my own problem-s...,NaN,"Yes, I use AI agents at work monthly or infreq...","No, but my development work has significantly ...",Marketing,NaN,AI agents have helped me solve complex problem...,AI agents have improved the quality of my code.,NaN,AI agents have improved collaboration within m...,AI agents have increased my productivity.;AI a...,NaN,It takes significant time and effort to learn ...,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,LangMem,NaN,IBM watsonx.ai,NaN,Honeycomb,NaN,Claude Code,NaN,When I need quick help troubleshooting,3,NaN,NaN

In [44]:
filt =df["Country"] == "South Korea"

In [45]:
df.loc[filt]

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1883,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),5.0,"Yes, I am not new to coding but am learning ne...",Technical documentation (is generated for/by t...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,5.0,"Architect, software or solutions",Less than 20 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was ultimately not...",Work,10.0,3.0,9.0,5.0,6.0,13.0,7.0,1.0,11.0,14.0,NaN,6.0,10.0,13.0,3.0,11.0,4.0,2.0,1.0,9.0,15.0,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have neither consider or transitioned into a...,NaN,NaN,South Korea,KRW\tSouth Korean won,NaN,Yes,Rust,Rust,Rust,NaN,NaN,Yes,MariaDB;MongoDB;MySQL,MariaDB;MongoDB;MySQL,MariaDB;MongoDB;MySQL,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,NaN,GitLab,GitLab,GitLab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Between 5 and 10 years,"Infrequently, less than once per year",NaN,3.0,NaN,5.0,1.0,9.0,2.0,12.0,8.0,13.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Somewhat trust,Very well at handling complex tasks,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,Testing code;Search for answers;Generating con...,I’ve become less confident in my own problem-s...,NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Decision intelligence;Dat...,NaN,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something,NaN,NaN,8.0
2873,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,16.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,24.0,"Developer, embedded applications or devices",NaN,NaN,NaN,No,Personal Project,9.0,5.0,3.0,6.0,8.0,4.0,7.0,1.0,2.0,10.0,NaN,9.0,7.0,5.0,6.0,3.0,2.0,4.0,8.0,1.0,10.0,NaN,Software Development,6.0,5.0,11.0,8.0,14.0,3.0,2.0,12.0,1.0,4.0,10.0,7.0,9.0,15.0,13.0,NaN,Yes,I have transitioned into a new career and/or i...,10.0,10.0,South Korea,KRW\tSouth Korean won,400000000.0,Yes,Bash/Shell (all shells);C;C++;HTML/CSS;Python;...,Assembly;HTML/CSS;Lisp;Python;Rust;Swift,HTML/CSS;Python;Rust,OpenSCAD,NaN,Yes,Elasticsearch;PostgreSQL;Redis;SQLite,DuckDB;PostgreSQL;Redis;SQLite;Valkey,PostgreSQL;Redis;SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);Cargo;Chocolatey;Clo...,Cargo;Chocolatey;Cloudflare;Docker;Firebase;Ho...,Cargo;Chocolatey;Cloudflare;Docker;Homebrew;np...,Python uv,Python uv,Yes,FastAPI;Flask;React,FastAPI;Flask;React;Svelte,FastAPI;Flask;React,NaN,NaN,Yes,Claude Code;Cursor;Neovim;Visual Studio Code;Zed,Claude Code;Neovim;Zed,Claude Code;Neovim;Zed,NaN,NaN,Polars;Large Language Model,c++23;Polars;Large Language Model;Pydantic,Polars;Large Language Model,NaN,NaN,Windows;MacOS;Windows Subsystem for Linux (WSL...,MacOS;Linux (non-WSL);Arch,GitHub;Google Workspace;Linear;Markdown File;O...,GitHub;Google Workspace;Linear;Markdown File;O...,GitHub;Google Workspace;Linear;Markdown File;O...,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Stack Overflow;Stack Exchange;Discord;Reddit;H...,NaN,NaN,Yes,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;Gemini (Flash general...,Anthropic: Claude Sonnet;Gemini (Flash general...,NaN,NaN,Yes,Multiple times per day,Between 10 and 15 years,I have never participated in Q&A on Stack Over...,Long-form articles;Lists of recommendations (t...,2.0,1.0,4.0,9.0,5.0,6.0,7.0,3.0,8.0,10.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Deployment and monitoring,Testing code;Committing and reviewing code;Gen...,Predictive analytics,NaN,"AI solutions that are almost right, but not qu...",Only for generating example codes for trying n...,"Yes, I use AI agents at work weekly",Not at all or minimally,Software engineering,NaN,NaN,AI agents have improved collaboration within m...,NaN,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code.,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,Ollama,NaN,Grafana + Prometheus,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,Having deep domain knowledge of obscure areas ...,293971.0,10.0
3064,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Volunteering (regularly),10.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,15.0,"Developer, front-end",Less than 20 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,2.0,1.0,3.0,6.0,7.0,8.0,4.0,5.0,9.0,NaN,10.0,2.0,7.0,5.0,4.0,1.0,8.0,6.0,3.0,9.0,NaN,Software Development,12.0,3.0,10.0,14.0,9.0,5.0,6.0,7.0,4.0,8.0,1.0,2.0,11.0,13.0,15.0,NaN,No,I have somewhat considered changing my career ...,5.0,7.0,South Korea,KRW\tSouth Korean won,72589992.0,Yes,HTML/CSS;JavaScript,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,MacOS,GitHub;GitLab,GitHub,GitHub,NaN,NaN,Stack Overflow;Bluesky,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 10 and 15 years,A few times per week,Job board,6.0,4.0,8.0,5.0,7.0,1.0,3.0,2.0,9.0,10.0,NaN,"Yes, definitely",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,Learning about a codebase;Project planning;Wri...,Testing code,Other (write in):,NaN,"AI solutions that are almost right, but not qu...","Some trainees tried to use it, reviewing on my...","Yes, I use AI agents at work weekly",Not at all or minimally,Other Industry purpose (write in):,Language processing;Vector databases for AI ap...,NaN,Write in the most significant benefit if not l...,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,Integrating AI agents with my existing tools a...,NaN,NaN,Ollama,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to think.,53348.0,5.0
3233,"I used to be a developer by profession, but no...",25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Videos (not associated ...,"No, I learned something that was not related t...",NaN,7.0,"Developer, game or graphics",20 to 99 employees,Individual contributor,In-person,No,Work,7.0,2.0,8.0,5.0,1.0,3.0,9.0,4.0,6.0,10.0,NaN,8.0,4.0,6.0,1.0,3.0,7.0,5.0,2.0,9.0,10.0,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,NaN,NaN,South Korea,KRW\tSouth Korean won,NaN,Yes,C;C#;C++,C;C#;C++,C;C#;C++,NaN,NaN,Yes,Oracle,Oracle,Oracle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Notepad++;Rider;Visual Studio;Visual Studio Code,Notepad++;Visual Studio,Notepad++;Visual Studio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;iOS;iPadOS,Windows,GitHub;GitLab;Notion,GitHub,GitHub,NaN,NaN,"Stack Overflow;GitHub (public projects, not pr...","Stack Overflow;GitHub (public projects, not pr...","Stack Overflow;GitHub (public projects, not pr...",NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Daily or almost daily,Between 1 and 3 years,Less than once per month or monthly,NaN,2.0,3.0,8.0,1.0,4.0,5.0,6.0,7.0,9.0,10.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase,Generating content or synthetic data,Project planning;Writing code;Debugging or fix...,Testing code;Committing and reviewing code;Pre...,Search for answers;Learning new concepts or te...,"AI solutions that are almost right, but not qu...",t,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering,Language processing,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot,NaN,When I need quick help troubleshooting,non-Hallucination,NaN,NaN
4438,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,None of the above,10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,12.0,"Developer, front-end",20 to 99 employees,Individual contributor,In-person,No,Work,6.0,1.0,2.0,8.0,4.0,5.0,7.0,9.0,3.0,10.0,NaN,5.0,1.0,2.0,8.0,3.0,7.0,4.0,9.0,6.0,10.0,NaN,Fintech,3.0,11.0,8.0,4.0,14.0,7.0,9.0,6.0,1.0,12.0,2.0,5.0,10.0,15.0,13.0,NaN,Yes,I have somewhat considered changing my career ...,4.0,2.0,South Korea,KRW\tSouth Korean won,66000000.0,Yes,HTML/CSS;JavaScript;PHP;SQL;TypeScript;Gleam,Elixir;Go;HTML/CSS;SQL;TypeScript;Gleam,HTML/CSS;SQL;TypeScript;Gleam,NaN,NaN,Yes,MariaDB;MongoDB;MySQL;PostgreSQL;Redis;Supabase,MariaDB;PostgreSQL;Supabase,MariaDB;PostgreSQL;Supabase,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Deno;Express;jQuery;Laravel;Next.js;Node.js;Re...,Next.js;Phoenix;React,Next.js;React,NaN,NaN,Yes,Cursor;Neovim;Visual Studio Code;Windsurf;Zed,Neovim,Neovim,NaN,NaN,Tailwind CSS 4;Large Language Model;Google Gem...,Tailwind CSS 4;Large Language Model;Google Gemini,Tailwind CSS 4;Large Language Model;Google Gemini,NaN,NaN,MacOS,MacOS,GitHub;Jira;Notion,GitHub;Jira;Notion,GitHub;Jira;Notion,NaN,NaN,"Discord;Reddit;Dev.to;GitHub (public projects,...","Discord;Reddit;Dev.to;GitHub (public projects,...","Discord;Reddit;Dev.to;GitHub (public projects,...",NaN,NaN,Yes,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;Gemini (Flash general...,Anthropic: Claude Sonnet;Gemini (Flash general...,NaN,NaN,Not sure/can't remember,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Long-form articles;Direct messag...,3.0,1.0,6.0,8.0,4.0,5.0,7.0,2.0,9.0,10.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Debuggi...,Project planning;Deployment and monitoring;Pre...,Committing and reviewing code,Documenting code;Creating or maintaining docum...,Testing code;Generating content or synthetic data,"AI solutions that are almost right, but not qu...",no. I use AI to generate a lot of code but bar...,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have helped me automate repetitive t...,AI agents have helped me solve complex problem...,AI agents have increased my productivity.,NaN,AI agents have improved the quality of my code...,NaN,Integrating AI agents with my existing tools a...,I am concerned about the accuracy of the infor...,NaN,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Grafana + Prometheus,NaN,ChatGPT;Claude Code;Google Gemini;Tabnine,NaN,I don’t think I’ll need help from people anymore,none,48505.0,6.0
5901,I am learning to code,18-24 years old,Some college/university study without earning ...,Student,None of the above,NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Videos (no...,7.0,Student,NaN,NaN,NaN,NaN,Personal Project,9.0,4.0,5.0,6.0,1.0,8.0,3.0,7.0,2.0,10.0,NaN,9.0,1.0,3.0,4.0,2.0,7.0,5.0,6.0,8.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have neither consider or transitioned into a...,5.0,3.0,South Korea,KRW\tSouth Korean won,NaN,Yes,Bash/Shell (all shells);HTML/CSS;Java;TypeScript,Bash/Shell (all shells);Go;HTML/CSS;SQL;TypeSc...,Bash/Shell (all shells);HTML/CSS;TypeScript,NaN,NaN,Yes,Pocketbase,BigQuery;SQLite;Pocketbase,Pocketbase,NaN,NaN,Yes,Bun;Cloudflare;Gradle;npm;pnpm;Vercel;Vite,Bun;Cloudflare;Netlify;pnpm;Vercel;Vite,Bun;Cloudflare;pnpm;Vercel;Vite,Scoop,Scoop,Yes,Astro;Next.js;Node.js;React;Spring Boot;Svelte,Astro;React;Svelte,Astro;React;Svelte,NaN,NaN,Yes,Cline and/or Roo;Cursor;IntelliJ IDEA;Visual S...,Windsurf;Zed,Windsurf;Zed,NaN,NaN,Tailwind CSS 4;Large Language Model;Google Gem...,Tailwind CSS 4;Large Language Model;Google Gem...,Tailwind CSS 4;Large Language Model;Google Gem...,NaN,NaN,Windows;Ubuntu;Android;Windows Subsystem for L...,Windows;Android,GitHub;Markdown File;Notion;Obsidian,GitHub;GitLab;Linear;Markdown File;Obsidian,GitHub;Markdown File;Obsidian,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Stack Overflow;Stack Exchange;Discord;Reddit;G...,NaN,NaN,Yes,Anthropic: Claude Sonnet;Gemini (Flash general...,Anthropic: Claude Sonnet;Gemini (Flash general...,Anthropic: Claude Sonnet;Gemini (Flash general...,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Coding challenges;Logic games/puzzles;Lists of...,3.0,2.0,4.0,1.0,7.0,9.0,6.0,5.0,8.0,10.0,NaN,"No, not at all",Less than half of the time,"Yes, I use AI tools weekly",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Debugging or fixing ...,NaN,Project planning;Writing code;Documenting code...,Testing code;Predictive analytics,NaN,"AI solutions that are almost right, but not quite",NaN,"Yes, I use AI agents at work monthly or infreq...","Yes, to a great extent",NaN,NaN,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,NaN,AI agents have helped me automate repetitive t...,NaN,My company's IT and/or InfoSec teams have stri...,I have concerns about the security and privacy...,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,OpenRouter,NaN,NaN,NaN,ChatGPT;Claude Code;Google Gemini;Roo code (Ro...,"T3 Chat, Windsurf",When I don’t trust AI’s answers;When I want to...,Asking good questions,NaN,NaN

In [47]:
country_grp["ConvertedCompYearly"].value_counts().head(50)

Country              ConvertedCompYearly
Afghanistan          1000.0                 1
                     8450.0                 1
                     65000.0                1
                     986.0                  1
                     5200.0                 1
                     282.0                  1
                     9858.0                 1
                     7042.0                 1
Albania              139218.0               1
                     67779.0                1
                     15.0                   1
                     17734.0                1
                     14187.0                1
                     118286.0               1
                     8.0                    1
                     236.0                  1
                     116014.0               1
                     34804.0                1
                     50000.0                1
                     17402.0                1
Algeria              4438.0                 1
                     1156.0                 1
                     7088.0                 1
                     98612.0                1
                     12000.0                1
                     23114.0                1
                     17.0                   1
                     6472.0                 1
                     2400.0                 1
                     1109.0                 1
                     50000.0                1
                     3852.0                 1
                     7705.0                 1
                     185.0                  1
                     20883.0                1
Andorra              400000.0               1
                     34804.0                1
                     348044.0               1
                     52207.0                1
Angola               13922.0                1
                     5234.0                 1
                     580073.0               1
                     200.0                  1
Antigua and Barbuda  1.0                    1
Argentina            100000.0               7
                     120000.0               6
                     42653.0                5
                     34122.0                4
                     50000.0                3
                     60000.0                3
Name: count, dtype: int64

In [50]:
country_grp["ConvertedCompYearly"].median().loc["Ukraine"]

np.float64(25021.0)

In [54]:
country_grp["ConvertedCompYearly"].agg(["median", "mean"])

                                                      median           mean
Country
Afghanistan                                           6121.0   12227.250000
Albania                                              26269.0   47973.583333
Algeria                                               6472.0   15935.400000
Andorra                                             200125.5  208763.750000
Angola                                                9578.0  149857.250000
Antigua and Barbuda                                      1.0       1.000000
Argentina                                            40000.0   46271.187500
Armenia                                               9076.0   25016.363636
Australia                                            97514.0  115941.413005
Austria                                              78310.0   79477.625000
Azerbaijan                                           29397.0   31202.333333
Bahrain                                              74240.5   74240.500000
Bangladesh                                            7895.5   15520.941667
Barbados                                             45450.5   45450.500000
Belarus                                              46614.5   58267.312500
Belgium                                              69609.0   84666.275229
Belize                                              102121.0  102121.000000
Benin                                                 1698.0    6816.333333
Bhutan                                               20361.0   20361.000000
Bolivia                                              18784.0   25214.307692
Bosnia and Herzegovina                               47000.0   51890.473684
Botswana                                              1277.0    1277.000000
Brazil                                               27306.0   51690.289515
Brunei Darussalam                                        NaN            NaN
Bulgaria                                             49817.5   54613.575949
Burundi                                               1697.0    1697.000000
Cambodia                                              1500.0    4694.000000
Cameroon                                              1265.5    4547.000000
Canada                                               87550.0  100143.382514
Cape Verde                                               NaN            NaN
Chile                                                33930.0   39241.252632
China                                                34125.0   47847.632479
Colombia                                             20500.0   31370.534351
Congo, Republic of the...                            42811.5   42811.500000
Costa Rica                                           59500.0   71422.111111
Croatia                                              46406.0   55424.829268
Cuba                                                 14041.5   71668.875000
Cyprus                                               92812.0   91799.041667
Czech Republic                                       60660.0   67003.573407
Côte d'Ivoire                                        33966.0   75877.200000
Democratic People's Republic of Korea                    NaN            NaN
Democratic Republic of the Congo                     30000.0   33000.000000
Denmark                                              98678.0  106030.465217
Djibouti                                              5833.0    5833.000000
Dominican Republic                                   27681.5   44179.600000
Ecuador                                              30000.0   40952.260870
Egypt                                                 6595.0   14453.921875
El Salvador                                          27000.0   41800.000000
Estonia                                              69609.0   76545.326923
Ethiopia                                               762.0   33087.166667
Fiji                                                     NaN            NaN
Finland                                              74249.0   85162.361257
France                                               63228.0   73778.737098
Gabon                                                    NaN            NaN
Gambia                                                   NaN            NaN
Georgia                                              53653.5   56644.250000
Germany                                              81210.0   86443.718356
Ghana                                                 2610.0    9833.318182
Greece                                               44260.0   53055.137931
Guatemala                                            29668.0   37647.896552
Guinea                                                2773.0    2773.000000
Guinea-Bissau                                            NaN            NaN
Guyana                                               35871.0   31566.333333
Haiti                                                 9149.0    9149.000000
Honduras                                             11982.0   22198.833333
Hong Kong (S.A.R.)                                   76433.0  111564.300000
Hungary                                              46266.0   55376.591716
Iceland                                             117637.0   88158.714286
India                                                17029.0   44291.789234
Indonesia                                             5638.0   17902.716049
Iran, Islamic Republic of...                         18516.0  277297.200000
Iraq                                                 18000.0   15420.666667
Ireland                                             116015.0  121326.818182
Isle of Man                                          83632.0   82521.444444
Israel                                              141188.0  131723.762712
Italy                                                47566.0   55911.454389
Jamaica                                              96796.5   96796.500000
Japan                                                58725.0   73440.617188
Jordan                                               30000.0   34879.826087
Kazakhstan                                           28381.5   33210.611111
Kenya                                                 6502.0   31946.506849
Kosovo                                               45245.5   50176.250000
Kuwait                                               26838.0   44543.600000
Kyrgyzstan                                           12605.0   41211.000000
Lao People's Democratic Republic                         7.0       7.000000
Latvia                                               51845.5   84648.050000
Lebanon                                              47000.0   77244.444444
Lesotho                                               2822.0    2822.000000
Libyan Arab Jamahiriya                                5541.0    5541.000000
Lithuania                                            66708.0   71457.739130
Luxembourg                                           98612.0  101348.235294
Madagascar                                            5288.0   16751.125000
Malawi                                               11252.5   11252.500000
Malaysia                                             18261.0   24403.434783
Maldives                                             24600.5   25039.500000
Mali                                                 11941.5   11941.500000
Malta                                                70189.0   69516.187500
Mauritania                                          121570.0  121570.000000
Mauritius                                            15976.0   16405.800000
Mexico                                               28951.0   37245.638743
Micronesia, Federated States of...                       1.0       1.000000
Moldova                                              29177.5   37324.500000
Mongolia                                             29757.0   31626.666667
Montenegro                                           42873.0   59133.916667
Morocco                                              21987.0   24531.695652
Mozambique                                            9381.0   36629.200000
Myanmar                                               5716.0    8404.200000
Namibia                                               3923.0    8024.333333
Nepal                                                 4060.0   25012.536585
Netherlands                                          81210.0  115292.822294
New Zealand                                          81318.0   81957.436464
Nicaragua                                            47000.0   67822.500000
Niger                                                    NaN            NaN
Nigeria                                               1291.0   63181.843137
Nomadic                                             135157.5  135473.833333
North Korea                                         233924.5  233924.500000
Norway                                               88945.0   99256.809783
Oman                                                390135.0  261217.000000
Pakistan                                              6321.0   12997.733333
Palau                                                    NaN            NaN
Palestine                                               78.0      78.000000
Panama                                               26400.0   55300.000000
Papua New Guinea                                      7574.0    7574.000000
Paraguay                                             21178.0   42256.000000
Peru                                                 16998.0   31296.575000
Philippines                                          12291.0   23956.063291
Poland                                               60038.0   97821.346350
Portugal                                             60908.0   74386.754630
Qatar                                                46111.0   46111.000000
Republic of Korea                                    44096.0   82366.555556
Republic of Moldova                                  46924.0   51249.400000
Republic of North Macedonia                          29472.0   31328.300000
Romania                                              57437.0   64200.027907
Russian Federation                                   38278.0   42168.700787
Rwanda                                               15591.5   16245.700000
Saint Lucia                                          30810.5   30810.500000
San Marino                                               NaN            NaN
Saudi Arabia                                         32789.0   49335.388889
Senegal                                              11786.5   11786.500000
Serbia                                               48000.0   57883.798165
Sierra Leone                                             NaN            NaN
Singapore                                            92563.0  131430.187500
Slovakia                                             55687.0   58923.165049
Slovenia                                             56847.0   73555.661290
Somalia                                               5300.0    6766.666667
South Africa                                         43412.0   78843.243243
South Korea                                          33072.0   44968.304348
Spain                                                62648.0   70795.607143
Sri Lanka                                            10391.0   21905.372881
Sudan                                                 4864.5    4864.500000
Suriname                                             18686.5   18686.500000
Swaziland                                             4848.5    8145.250000
Sweden                                               70440.0   73943.915074
Switzerland                                         142592.0  151290.444976
Syrian Arab Republic                                  9845.5   13265.166667
Taiwan                                               33886.0   41913.571429
Tajikistan                                               NaN            NaN
Thailand                                             32123.0   47619.614035
Timor-Leste                                              NaN            NaN
Togo                                                   711.0    3688.333333
Trinidad and Tobago                                  29595.0   37923.250000
Tunisia                                               6517.0   13840.520000
Turkey                                               29000.0   38163.090426
Turkmenistan                                         35000.0   35000.000000
Uganda                                                4588.0   14159.833333
Ukraine                                              25021.0  105101.259520
United Arab Emirates                                 54460.0  105481.808511
United Kingdom of Great Britain and Northern Ir...   94618.0  112948.493943
United Republic of Tanzania                           5014.0   12041.200000
United States of America                            150000.0  179804.501621
Uruguay                                              49338.0   78567.414634
Uzbekistan                                            9675.0   12593.555556
Venezuela, Bolivarian Republic of...                  9000.0   17008.400000
Viet Nam                                              7642.0  189894.192982
Yemen                                                 5545.5   17582.500000
Zambia                                                1966.5    6594.875000
Zimbabwe                                             17500.0   25662.500000

In [59]:
filt =df["Country"] == "South Korea"
df.loc[filt]["LanguageHaveWorkedWith"].str.contains("Python").sum()

np.int64(23)

In [70]:
country_grp["LanguageHaveWorkedWith"].apply(lambda x: x.str.contains("Python").sum() / x.count() * 100)

/tmp/ipykernel_216203/2906370951.py:1: RuntimeWarning: invalid value encountered in scalar divide
  country_grp["LanguageHaveWorkedWith"].apply(lambda x: x.str.contains("Python").sum() / x.count() * 100)

Country
Afghanistan                                              44.444444
Albania                                                  47.619048
Algeria                                                  63.888889
Andorra                                                  40.000000
Angola                                                   33.333333
Antigua and Barbuda                                     100.000000
Argentina                                                54.271357
Armenia                                                  35.000000
Australia                                                56.258412
Austria                                                  57.069409
Azerbaijan                                               50.000000
Bahrain                                                  80.000000
Bangladesh                                               49.438202
Barbados                                                 66.666667
Belarus                                                  31.818182
Belgium                                                  56.655290
Belize                                                   50.000000
Benin                                                    60.000000
Bhutan                                                   66.666667
Bolivia                                                  50.000000
Bosnia and Herzegovina                                   37.037037
Botswana                                                 50.000000
Brazil                                                   57.567185
Brunei Darussalam                                       100.000000
Bulgaria                                                 47.136564
Burundi                                                  50.000000
Cambodia                                                 44.444444
Cameroon                                                 66.666667
Canada                                                   57.634228
Cape Verde                                              100.000000
Chile                                                    72.566372
China                                                    68.468468
Colombia                                                 65.317919
Congo, Republic of the...                                33.333333
Costa Rica                                               66.666667
Croatia                                                  43.564356
Cuba                                                     75.000000
Cyprus                                                   45.454545
Czech Republic                                           54.756871
Côte d'Ivoire                                            66.666667
Democratic People's Republic of Korea                   100.000000
Democratic Republic of the Congo                         50.000000
Denmark                                                  53.356890
Djibouti                                                  0.000000
Dominican Republic                                       55.000000
Ecuador                                                  55.555556
Egypt                                                    43.269231
El Salvador                                              30.000000
Estonia                                                  44.117647
Ethiopia                                                 40.740741
Fiji                                                    100.000000
Finland                                                  64.315353
France                                                   62.739097
Gabon                                                          NaN
Gambia                                                  100.000000
Georgia                                                  50.000000
Germany                                                  60.286225
Ghana                                                    71.428571
Greece                                                   51.801802
Guatemala                                                58.620690
Guinea                                                  100.000000
Guinea-Bissau                                           100.000000
Guyana                                                   50.000000
Haiti                                                   100.000000
Honduras                                                 40.000000
Hong Kong (S.A.R.)                                       56.060606
Hungary                                                  54.298643
Iceland                                                  77.777778
India                                                    57.524752
Indonesia                                                48.051948
Iran, Islamic Republic of...                             46.280992
Iraq                                                     50.000000
Ireland                                                  53.886010
Isle of Man                                              50.000000
Israel                                                   65.283019
Italy                                                    57.978723
Jamaica                                                  50.000000
Japan                                                    58.381503
Jordan                                                   44.000000
Kazakhstan                                               60.714286
Kenya                                                    65.289256
Kosovo                                                   66.666667
Kuwait                                                   75.000000
Kyrgyzstan                                               44.444444
Lao People's Democratic Republic                         50.000000
Latvia                                                   56.140351
Lebanon                                                  60.000000
Lesotho                                                 100.000000
Libyan Arab Jamahiriya                                    0.000000
Lithuania                                                51.041667
Luxembourg                                               52.631579
Madagascar                                               62.500000
Malawi                                                   50.000000
Malaysia                                                 57.746479
Maldives                                                 66.666667
Mali                                                    100.000000
Malta                                                    68.421053
Mauritania                                                0.000000
Mauritius                                                70.000000
Mexico                                                   57.613169
Micronesia, Federated States of...                             NaN
Moldova                                                  44.444444
Mongolia                                                100.000000
Montenegro                                               42.857143
Morocco                                                  62.000000
Mozambique                                               66.666667
Myanmar                                                  53.846154
Namibia                                                  50.000000
Nepal                                                    55.714286
Netherlands                                              57.901391
New Zealand                                              56.431535
Nicaragua                                                40.000000
Niger                                                   100.000000
Nigeria                                                  54.794521
Nomadic                                                  62.962963
North Korea                                              75.000000
Norway                                                   50.691244
Oman                                                     40.000000
Pakistan                                                 51.612903
Palau                                                   100.000000
Palestine                                                75.000000
Panama                                                   70.000000
Papua New Guinea                                         50.000000
Paraguay                                                 42.105263
Peru                                                     50.980392
Philippines                                              59.829060
Poland                                                   56.877323
Portugal                                                 60.546875
Qatar                                                    25.000000
Republic of Korea                                        61.764706
Republic of Moldova                                      14.285714
Republic of North Macedonia                              47.058824
Romania                                                  46.075085
Russian Federation                                       59.782609
Rwanda                                                   75.000000
Saint Lucia                                             100.000000
San Marino                                                0.000000
Saudi Arabia                                             65.517241
Senegal                                                  25.000000
Serbia                                                   52.112676
Sierra Leone                                              0.000000
Singapore                                                65.384615
Slovakia                                                 56.204380
Slovenia                                                 56.164384
Somalia                                                  25.000000
South Africa                                             55.357143
South Korea                                              58.974359
Spain                                                    60.120846
Sri Lanka                                                66.233766
Sudan                                                          NaN
Suriname                                                100.000000
Swaziland                                                50.000000
Sweden                                                   51.504425
Switzerland                                              63.035019
Syrian Arab Republic                                     55.555556
Taiwan                                                   63.000000
Tajikistan                                               50.000000
Thailand                                                 57.281553
Timor-Leste                                               0.000000
Togo                                                     33.333333
Trinidad and Tobago                                      28.571429
Tunisia                                                  63.636364
Turkey                                                   52.000000
Turkmenistan                                              0.000000
Uganda                                                   72.222222
Ukraine                                                  46.098439
United Arab Emirates                                     57.352941
United Kingdom of Great Britain and Northern Ireland     55.126141
United Republic of Tanzania                              33.333333
United States of America                                 63.425995
Uruguay                                                  53.061224
Uzbekistan                                               66.666667
Venezuela, Bolivarian Republic of...                     54.761905
Viet Nam                                                 66.666667
Yemen                                                    50.000000
Zambia                                                   70.000000
Zimbabwe                                                 63.636364
Name: LanguageHaveWorkedWith, dtype: float64